# Generated by Django 4.2.6 on 2023-10-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('username', models.CharField(max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('confirm', models.CharField(max_length=100)),
                ('comments', models.CharField(max_length=200)),



                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
            ],
        ),
    ]
