# Generated by Django 4.2.6 on 2023-10-23 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='comments',
            field=models.CharField(default='not specified', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='not specified', max_length=100, unique=True),
        ),
    ]
