# Generated by Django 4.2.6 on 2023-10-23 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_comments_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='not specified', max_length=100),
        ),
    ]
