# Generated by Django 4.2.6 on 2023-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_rename_username_customer_username2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='username2',
            field=models.CharField(max_length=100),
        ),
    ]
