# Generated by Django 4.2.6 on 2023-10-23 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_username2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username2',
        ),
    ]
