# Generated by Django 4.2.6 on 2023-10-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_remove_customer_username2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username2',
            field=models.CharField(default='UN', max_length=100),
            preserve_default=False,
        ),
    ]
