# Generated by Django 4.2.6 on 2023-10-23 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_username2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='username',
            field=models.CharField(default='-', max_length=100),
            preserve_default=False,
        ),
    ]
