# Generated by Django 4.2.6 on 2023-10-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_customermodel_delete_customer2'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='password',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AddField(
            model_name='customermodel',
            name='passwordconfirm',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
