# Generated by Django 4.2.6 on 2023-10-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=100)),
                ('comments', models.CharField(default='not specified', max_length=200)),
                ('password', models.CharField(default='-', max_length=100)),
                ('passwordconfirm', models.CharField(default='-', max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
