# Generated by Django 4.2.6 on 2023-10-24 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='comments',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='-', max_length=200),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
