# Generated by Django 4.2.6 on 2023-10-13 03:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
