# Generated by Django 4.2.6 on 2023-10-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='userName',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
