# Generated by Django 4.2.6 on 2023-10-31 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.CharField(default='?', max_length=200),
        ),
        migrations.AddField(
            model_name='customer',
            name='firstname',
            field=models.CharField(default='?', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='lastname',
            field=models.CharField(default='?', max_length=100),
        ),
    ]
