# Generated by Django 4.2.6 on 2023-10-14 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalmodel',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(75)]),
        ),
    ]
