# Generated by Django 4.2.6 on 2023-10-14 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentalcar', '0002_alter_rentalmodel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalmodel',
            name='comments',
            field=models.CharField(default='no comments', max_length=50),
        ),
    ]
